version: '3.1'
services:
  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: ./dockerfile
    command:
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=2
    ports:
      - ${PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-root}
      MYSQL_ROOT_HOST: "%"
    restart: on-failure
    volumes:
      - ${DATA_DIR:-~/Sites/_mysql}:/var/lib/mysql:delegated

networks:
  default:
    external:
      name: nginx-proxy